### ISSUE TITLE
Override the entrypoint command using the container spec

### ISSUE THREAD

**Issue by dontseyit** [ghga-de/charts#67]
If there are multiple subcommands as entrypoint to the service the command should be configurable in `values.yaml`.
Currently it's now in [deployment.yml](https://github.com/ghga-de/charts/blob/4dfbfe2dd4117e192b06d391e1294cd23009ff7a/charts/file-ingest/templates/deployment.yml#L34). The command field in the container spec should be used.

**Comment by ckaipf** [comment]
Could look like this in `values.yaml`:

```yaml
image:
  name: "ghga/file-ingest-service"
  command: ["run-rest"]
```

Maybe this can be refactored by changing this
https://github.com/ghga-de/charts/blob/4dfbfe2dd4117e192b06d391e1294cd23009ff7a/charts/ghga-common/templates/_command-args.tpl#L15

to `{{ .Values.image.command }}`.
